n=input("enter the comma seperated multiple values::")
list1=n.split(",")
t=tuple(list1)
print("list is:",list1,"\n","tuples:",t)

values=input("enter the multiple values seprated by commas::")
list=values.split(",")
print("the list of elements is::",list)
tuple=tuple(list)
print("the tuple of elements::",tuple)
